modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "harmonia"
version = "${version}"
displayName = "Harmonia"
authors = "wasabiwhisper"
description = '''
Add compatability between Cadmus and Xaero's Worldmap.
'''
logoFile = "icon.png"

[[dependencies.harmonia]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harmonia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harmonia]]
modId = "cadmus"
mandatory = true
versionRange = "[${cadmus_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harmonia]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourceful_lib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harmonia]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[${xaeros_world_map_version},)"
ordering = "NONE"
side = "CLIENT"